/**
 * Expose the curated skill pack where the Claude Code host actually looks.
 *
 * THE DEFECT THIS FIXES
 * ─────────────────────
 * `writeSkillFiles()` installs the pack under `.moe/skills/<name>/SKILL.md`,
 * and `recommendSkill.ts` hands every seat a `nextAction.recommendedSkill`
 * naming one of those directories. The agent wrappers then print
 * `[skill] Recommending '<name>' for this phase.` and the role docs instruct
 * the agent to load it before the hinted tool.
 *
 * But Claude Code discovers project skills under `.claude/skills/`, not
 * `.moe/skills/`. Nothing in the repo ever wrote there, so every one of those
 * ten recommendations pointed at a skill the Skill tool could not resolve:
 *
 *     Skill(skill="explore-before-assume") -> "Unknown skill"
 *
 * Reported from a live worker seat 2026-09-14; reproduced against a project
 * whose `.moe/skills/` held all 15 skills while `.claude/skills/` did not
 * exist. The comment at scripts/moe-agent.sh ("Skills live on disk under
 * .moe/skills/; the agent loads them via its host's Skill tool when relevant")
 * records the assumption that was false.
 *
 * WHY A LINK AND NOT A COPY
 * ─────────────────────────
 * `writeSkillFiles()` upgrades a skill in place by restamping files that carry
 * a stale `moe-generated: sha=` marker. A plain copy taken at init would not
 * see those upgrades and would silently serve a stale skill body forever. A
 * per-skill symlink keeps `.moe/skills/` the single source of truth. Copying
 * is the fallback only where symlinks are unavailable (Windows without
 * Developer Mode), and those copies are refreshed on every call so they
 * converge on the next daemon start rather than pinning the init-time body.
 *
 * WHAT IT WILL NOT TOUCH
 * ──────────────────────
 * Only entries that are absent, or that we previously created (a symlink
 * resolving into `.moe/skills/`, or a copied tree carrying the generated
 * marker), are written. A real user-authored `.claude/skills/<name>/` is left
 * strictly alone — the user's own skill of the same name wins.
 */

import fs from 'fs';
import path from 'path';
import { logger } from './logger.js';

export interface ClaudeSkillsLinkResult {
  /** Skill directories exposed as symlinks into `.moe/skills/`. */
  linked: string[];
  /** Skill directories copied because symlinking was unavailable. */
  copied: string[];
  /** Skill directories skipped because a user-owned entry already sits there. */
  skippedUserOwned: string[];
  /** True when `.moe/skills/` did not exist, so there was nothing to expose. */
  noSkillPack: boolean;
}

/** Marker that identifies a file as generated by Moe rather than user-authored. */
const GENERATED_MARKER = 'moe-generated:';

/**
 * Mirror `.moe/skills/<name>/` into `.claude/skills/<name>/` so the Claude Code
 * Skill tool can resolve the names the daemon recommends.
 *
 * Idempotent: safe to call on every daemon start. Never throws — a project that
 * cannot host `.claude/skills/` (read-only checkout, permissions) degrades to
 * the previous behaviour of skills being merely unreachable, which must not
 * take the daemon down with it.
 */
export function linkClaudeSkills(projectRoot: string): ClaudeSkillsLinkResult {
  const result: ClaudeSkillsLinkResult = {
    linked: [],
    copied: [],
    skippedUserOwned: [],
    noSkillPack: false,
  };

  // MUST be absolute before we build any symlink target. A relative link target
  // is resolved against the LINK's own directory (.claude/skills/), not the
  // process cwd, so a relative projectRoot yields
  // `.claude/skills/<root>/.moe/skills/<name>` — a dead link that reports
  // success. The daemon takes its project path from argv, which may be
  // relative, so this is reachable in production and not a test artifact.
  const root = path.resolve(projectRoot);

  const moeSkillsDir = path.join(root, '.moe', 'skills');
  if (!fs.existsSync(moeSkillsDir)) {
    result.noSkillPack = true;
    return result;
  }

  const targetDir = path.join(root, '.claude', 'skills');
  try {
    fs.mkdirSync(targetDir, { recursive: true });
  } catch (error) {
    logger.warn({ error, targetDir }, 'Failed to create .claude/skills; recommended skills will not resolve');
    return result;
  }

  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(moeSkillsDir, { withFileTypes: true });
  } catch (error) {
    logger.warn({ error, moeSkillsDir }, 'Failed to read .moe/skills');
    return result;
  }

  for (const entry of entries) {
    // Only skill directories. manifest.json / LICENSE-VENDORED.md are Moe
    // bookkeeping and are not skills the host should try to load.
    if (!entry.isDirectory()) continue;

    const name = entry.name;
    const source = path.join(moeSkillsDir, name);
    const target = path.join(targetDir, name);

    // A skill directory without a SKILL.md is not loadable; exposing it would
    // just produce a different flavour of "unknown skill".
    if (!fs.existsSync(path.join(source, 'SKILL.md'))) continue;

    const ownership = classifyExisting(target, source);
    if (ownership === 'user-owned') {
      result.skippedUserOwned.push(name);
      continue;
    }
    if (ownership === 'ours-symlink') {
      // Already pointing at the source — nothing to do, and re-creating it
      // would briefly leave the skill unresolvable.
      result.linked.push(name);
      continue;
    }
    if (ownership === 'ours-copy') {
      // Refresh so an upgraded .moe/skills body actually reaches the host.
      if (copyTree(source, target)) result.copied.push(name);
      continue;
    }

    if (trySymlink(source, target)) {
      result.linked.push(name);
    } else if (copyTree(source, target)) {
      result.copied.push(name);
    }
  }

  return result;
}

type Ownership = 'absent' | 'ours-symlink' | 'ours-copy' | 'user-owned';

/**
 * Decide whether we may write over `target`.
 *
 * `lstatSync` rather than `statSync` on purpose: we need to see the symlink
 * itself, not what it resolves to, or a link we created looks like a directory.
 */
function classifyExisting(target: string, source: string): Ownership {
  let stat: fs.Stats;
  try {
    stat = fs.lstatSync(target);
  } catch {
    return 'absent';
  }

  if (stat.isSymbolicLink()) {
    try {
      // Compare resolved paths so a relative link still matches.
      const resolved = fs.realpathSync(target);
      if (resolved === fs.realpathSync(source)) return 'ours-symlink';
    } catch {
      // Dangling link — it was ours and the source moved. Replacing it is
      // strictly better than leaving a broken entry behind.
      try {
        fs.unlinkSync(target);
      } catch {
        return 'user-owned';
      }
      return 'absent';
    }
    // Points somewhere else entirely: the user aimed it deliberately.
    return 'user-owned';
  }

  // A directory we copied carries the generated marker in its SKILL.md.
  try {
    const body = fs.readFileSync(path.join(target, 'SKILL.md'), 'utf-8');
    return body.includes(GENERATED_MARKER) ? 'ours-copy' : 'user-owned';
  } catch {
    return 'user-owned';
  }
}

/**
 * Symlink `target` -> `source`, returning false rather than throwing when the
 * platform refuses (Windows without Developer Mode is the common case).
 */
function trySymlink(source: string, target: string): boolean {
  try {
    // 'junction' is ignored on POSIX and is the one symlink flavour Windows
    // allows unprivileged for directories.
    fs.symlinkSync(source, target, process.platform === 'win32' ? 'junction' : 'dir');
    return true;
  } catch (error) {
    logger.debug({ error, source, target }, 'Symlink unavailable for skill; falling back to copy');
    return false;
  }
}

/** Recursively copy a skill directory. Returns false on any failure. */
function copyTree(source: string, target: string): boolean {
  try {
    fs.mkdirSync(target, { recursive: true });
    for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
      const from = path.join(source, entry.name);
      const to = path.join(target, entry.name);
      if (entry.isDirectory()) {
        if (!copyTree(from, to)) return false;
      } else if (entry.isFile()) {
        fs.copyFileSync(from, to);
      }
    }
    return true;
  } catch (error) {
    logger.warn({ error, source, target }, 'Failed to copy skill into .claude/skills');
    return false;
  }
}
