const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test } = require('node:test');
const ts = require('typescript');

// Legacy task time caps (task.budget) are retired: neither the board card nor
// the task detail may render them. Both renderers run from their production
// sources - media/board.js for the card and the webview HTML generated by
// TaskDetailPanel for the detail - so nothing here re-implements them.
const boardScriptPath = path.join(__dirname, '../media/board.js');
const panelPath = path.join(__dirname, '../src/panels/TaskDetailPanel.ts');
const providerPath = path.join(__dirname, '../src/providers/BoardViewProvider.ts');

function transpile(sourcePath) {
    return ts.transpileModule(fs.readFileSync(sourcePath, 'utf8'), {
        compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true }
    }).outputText;
}

const boardScript = fs.readFileSync(boardScriptPath, 'utf8');
const panelSource = transpile(panelPath);
const providerSource = transpile(providerPath);

// Every derived duration is measured against a fixed "now" of 10:10.
const at = hhmm => `2026-09-11T${hhmm}:00.000Z`;

function pinClock(context) {
    vm.runInContext(`Date.now = function () { return ${Date.parse(at('10:10'))}; };`, context);
}

// A stub that throws on any member it does not define, so a new IDE, DOM or
// transport dependency fails loudly instead of rendering against undefined.
function strict(name, members) {
    return new Proxy(members, {
        get(target, key) {
            if (typeof key === 'symbol' || key in target) { return Reflect.get(target, key); }
            throw new Error(`unexpected access to ${name}.${key}`);
        }
    });
}

const subscription = () => strict('Disposable', { dispose() {} });
const fakeUri = (base, ...segments) => ({ path: [base.path, ...segments].join('/') });
const fakeWebview = members => ({
    cspSource: 'vscode-webview://moe-test', asWebviewUri: uri => `vscode-webview://moe-test${uri.path}`, ...members
});

// Runs a transpiled extension module that may require only the given
// dependencies; any other require() throws.
function loadModule(source, filename, dependencies) {
    const module = { exports: {} };
    const context = vm.createContext({
        exports: module.exports, module, console,
        require: name => {
            if (Object.prototype.hasOwnProperty.call(dependencies, name)) { return dependencies[name]; }
            throw new Error(`unexpected require from ${path.basename(filename)}: ${name}`);
        }
    });
    pinClock(context);
    vm.runInContext(source, context, { filename });
    return module.exports;
}

// Renders one card with the real renderTaskCard of a freshly loaded board.js.
// The script's load-time retry timers are real and always cleared.
function renderCard(task) {
    const clears = [];
    const ignore = () => {};
    const byId = strict('document.getElementById', Object.fromEntries(['epicFilter', 'addEpicBtn', 'searchInput', 'searchClear']
        .map(id => [id, strict(`#${id}`, { addEventListener: ignore })])));
    const context = vm.createContext({
        acquireVsCodeApi: () => strict('vscodeApi', { getState: () => undefined, setState: ignore, postMessage: ignore }),
        document: strict('document', {
            addEventListener: ignore, body: strict('document.body', { addEventListener: ignore }), getElementById: id => byId[id]
        }),
        window: strict('window', { addEventListener: ignore }),
        setInterval: (fn, ms) => { const h = setInterval(fn, ms); clears.push(() => clearInterval(h)); return h; },
        setTimeout: (fn, ms) => { const h = setTimeout(fn, ms); clears.push(() => clearTimeout(h)); return h; },
        clearInterval, clearTimeout, console
    });
    try {
        pinClock(context);
        vm.runInContext(boardScript, context, { filename: boardScriptPath });
        return context.renderTaskCard(task, [], task.status);
    } finally {
        clears.forEach(clear => clear());
    }
}

// Opens the real TaskDetailPanel through createOrShow and returns the webview
// HTML it generated; the panel is disposed even when rendering throws.
function renderDetail(task) {
    const webview = fakeWebview({ html: '', onDidReceiveMessage: subscription });
    const panel = strict('WebviewPanel', { webview: strict('Webview', webview), onDidDispose: subscription, dispose() {} });
    const { TaskDetailPanel } = loadModule(panelSource, panelPath, {
        vscode: {
            ViewColumn: strict('vscode.ViewColumn', { One: 1 }), Uri: strict('vscode.Uri', { joinPath: fakeUri }),
            window: strict('vscode.window', { createWebviewPanel: () => panel })
        }
    });
    const state = { tasks: [task], epics: [] };
    const client = strict('MoeDaemonClient', { currentState: state, onStateChanged: subscription });
    let opened;
    try {
        opened = TaskDetailPanel.createOrShow({ path: '/extension' }, client, task.id, state);
        return webview.html;
    } finally {
        if (opened) { opened.dispose(); }
    }
}

// The badge styling lives in the board webview stylesheet, which
// BoardViewProvider emits; read it from the provider's real HTML.
function boardStylesheet() {
    const dependencies = { vscode: { Uri: strict('vscode.Uri', { joinPath: fakeUri }) } };
    // Only message handlers reach the panels; building the HTML must not.
    for (const panel of ['EpicDetailPanel', 'TaskCreatePanel', 'PlanReviewPanel', 'TaskDetailPanel']) {
        dependencies[`../panels/${panel}`] = strict(`require('../panels/${panel}')`, {});
    }
    const { BoardViewProvider } = loadModule(providerSource, providerPath, dependencies);
    const events = { onStateChanged: subscription, onConnectionChanged: subscription, onActivityLog: subscription };
    const provider = new BoardViewProvider({ path: '/extension' }, strict('MoeDaemonClient', events));
    try {
        const style = /<style>([\s\S]*?)<\/style>/.exec(provider.getHtmlContent(strict('Webview', fakeWebview())));
        if (!style) { throw new Error('BoardViewProvider emitted no <style> block'); }
        return style[1];
    } finally {
        provider.dispose();
    }
}

const TITLE = 'Retire the task time cap';

function makeTask(overrides = {}) {
    return {
        id: 'task-legacy-cap-fixture', epicId: 'epic-legacy-cap-fixture', title: TITLE, status: 'WORKING', priority: 'MEDIUM',
        description: 'Show elapsed time without a cap.', definitionOfDone: ['Cards show elapsed time only'], implementationPlan: [],
        assignedWorkerId: 'worker-1', prLink: null, reopenCount: 0, reopenReason: null, order: 1, comments: [], ...overrides
    };
}

// Claimed at 10:00 and still running at the fixed 10:10 "now".
const claimedTask = () => makeTask({ metrics: { firstClaimAt: at('10:00') } });

// Caps the old renderers turned into a denominator, a status mark or a remaining-time KPI.
const POPULATED_CAPS = {
    'a cap well above the elapsed time': { wallClockMs: 60 * 60 * 1000 },
    'a nearly used-up cap with a warning': { wallClockMs: 12 * 60 * 1000, warnedAt: at('10:08') },
    'an exceeded cap that was escalated': { wallClockMs: 5 * 60 * 1000, warnedAt: at('10:04'), escalatedAt: at('10:05') },
    'a zero cap': { wallClockMs: 0 }
};

// Null and malformed legacy data must be ignored the same way, without throwing.
const MALFORMED_CAPS = {
    'an explicit null': null, 'an explicit undefined': undefined, 'an empty object': {},
    'a null cap': { wallClockMs: null }, 'a non-numeric cap': { wallClockMs: 'soon' },
    'a negative cap': { wallClockMs: -60 * 1000 }, 'a string': '1h', 'a number': 60 * 60 * 1000, 'an array': [60 * 60 * 1000]
};

// Equal markup passes; otherwise fail on the first differing line, so the
// diff shows the rendered change instead of a truncated page.
function assertSameMarkup(actual, expected, message) {
    if (actual === expected) { return; }
    let i = 0;
    while (actual[i] === expected[i]) { i++; }
    const from = i === 0 ? 0 : actual.lastIndexOf('\n', i - 1) + 1;
    assert.equal(actual.slice(from, i + 200), expected.slice(from, i + 200), message);
}

// Renders the task bare and under every legacy cap shape; all must match.
function assertCapsIgnored(render, task, label = 'task') {
    const bare = render(task);
    for (const [name, cap] of Object.entries({ ...POPULATED_CAPS, ...MALFORMED_CAPS })) {
        assertSameMarkup(render({ ...task, budget: cap }), bare, `${label} with ${name}`);
    }
    return bare;
}

const compact = html => html.replace(/>\s+</g, '><').trim();
const firstMatch = (pattern, text) => { const match = pattern.exec(text); return match ? match[0] : null; };
const titleOf = card => firstMatch(/<div class="task-title">.*?<\/div>/, card);
const titleLine = (badge = '') => `<div class="task-title">${TITLE}${badge}</div>`;
const elapsedBadge = elapsed => `  <span class="task-elapsed" title="Wall-clock: ${elapsed}">[${elapsed}]</span>`;
const kpiRowOf = html => firstMatch(/<div class="kpi-row">.*<\/div>/, html);
const kpiRow = (...kpis) => `<div class="kpi-row">${kpis.join('')}</div>`;
const kpi = (label, value) => `<div class="kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${value}</div></div>`;
const SECTION_METRICS = '<div class="section-title">Metrics</div>';

// The detail's Metrics section, from its heading up to the Comments section.
function metricsSectionOf(html) {
    const start = html.indexOf(SECTION_METRICS);
    return start < 0 ? '' : compact(html.slice(start, html.indexOf('<!-- Comments -->', start)));
}

// [case, task metrics, card elapsed label, detail Wall-clock KPI]; null means none is shown.
const DURATION_CASES = [
    ['a running task measured from first claim to now', { firstClaimAt: at('10:00') }, '10m', '10m'],
    ['a finished task measured from first claim to doneAt', { firstClaimAt: at('10:00'), doneAt: at('10:05') }, '5m', '5m'],
    ['a recorded duration preferred over timestamps', { firstClaimAt: at('10:00'), wallClockMs: 2 * 60 * 1000 }, '2m', '2m'],
    ['a recorded duration without a first claim', { wallClockMs: 2 * 60 * 1000 }, null, '2m'],
    ['an unparseable first claim', { firstClaimAt: 'not-a-date' }, '0s', null],
    ['an unparseable doneAt', { firstClaimAt: at('10:00'), doneAt: 'soon' }, '0s', null],
    ['a first claim in the future', { firstClaimAt: at('10:30') }, '0s', '0s'],
    ['a doneAt before the first claim', { firstClaimAt: at('10:00'), doneAt: at('09:00') }, '0s', '0s'],
    ['a negative recorded duration', { firstClaimAt: at('10:00'), wallClockMs: -5000 }, '0s', '0s']
];

// A reviewed task carrying every live metric and supplement the renderers show.
const richTask = () => makeTask({
    status: 'REVIEW', priority: 'HIGH', hasPendingQuestion: true,
    implementationPlan: [{ stepId: 'step-1', description: 'Red first', status: 'COMPLETED' },
        { stepId: 'step-2', description: 'Green', status: 'IN_PROGRESS' }, { stepId: 'step-3', description: 'Review', status: 'PENDING' }],
    metrics: { plannedStepCount: 3, executedStepCount: 2, reopenCount: 2, rejectCount: 1, firstClaimAt: at('08:00'), doneAt: at('09:30') },
    planCritiqueResult: { verdict: 'block', concerns: ['Scope <too> wide'], reviewedBy: 'governor-1', reviewedAt: at('07:00') },
    failedDodItems: [{ item: 'Tests pass' }, { item: 'Tests pass' }, { item: 'Docs & notes' }],
    priorHandoffs: [{ from: 'worker-<a>', to: 'worker-b', createdAt: at('08:30'),
        whatIsDone: 'Steps 1-2', whatRemains: 'Step 3', pitfalls: ' ', openQuestions: 'None' }]
});

test('board card of a claimed task shows only its elapsed wall-clock under every legacy cap shape', () => {
    assert.equal(titleOf(assertCapsIgnored(renderCard, claimedTask())), titleLine(elapsedBadge('10m')));
});

test('board card of a never-claimed task has no elapsed badge under every legacy cap shape', () => {
    assert.equal(titleOf(assertCapsIgnored(renderCard, makeTask())), titleLine());
});

test('board card shows no badge for a recorded duration without a first claim', () => {
    const card = assertCapsIgnored(renderCard, makeTask({ metrics: { wallClockMs: 2 * 60 * 1000 } }));
    assert.equal(titleOf(card), titleLine());
});

test('board card elapsed badge keeps its duration rules under every legacy cap shape', () => {
    for (const [name, metrics, elapsed] of DURATION_CASES) {
        const card = assertCapsIgnored(renderCard, makeTask({ metrics }), name);
        assert.equal(titleOf(card), titleLine(elapsed == null ? '' : elapsedBadge(elapsed)), name);
    }
});

test('board stylesheet styles the class the elapsed badge emits and drops the retired class', () => {
    const badge = /<span class="([\w-]+)" title="Wall-clock: 10m">\[10m\]<\/span>/.exec(renderCard(claimedTask()));
    assert.notEqual(badge, null, 'the claimed card renders an elapsed badge');
    const stylesheet = boardStylesheet();
    assert.deepEqual(stylesheet.match(new RegExp(`\\.${badge[1]}(?=\\s*\\{)`, 'g')), [`.${badge[1]}`]);
    assert.deepEqual(stylesheet.match(/\.task-budget\b/g), null);
});

test('board card keeps its chips and elapsed badge for a task with every live metric', () => {
    const card = assertCapsIgnored(renderCard, richTask());
    assert.equal(titleOf(card), titleLine(elapsedBadge('1h 30m')));
    assert.equal(compact(firstMatch(/<div class="task-meta">[\s\S]*?<\/div>/, card)), '<div class="task-meta">'
        + '<span class="chip chip-high">High</span><span class="chip chip-progress-active">1/3</span>'
        + '<span class="chip chip-question" title="Pending question">?</span>'
        + '<span class="chip chip-reopen" title="Reopened 2 time(s)">↻ 2</span>'
        + '<span class="chip chip-handoff" title="1 prior hand-off(s)">🤝 1</span>'
        + '<span class="chip chip-critique" title="Scope &lt;too&gt; wide">⚠ critique blocked</span>'
        + '<span class="chip chip-id">TURE</span><span class="task-worker">worker-1</span></div>');
});

test('task detail markup is identical with or without any legacy cap', () => {
    assert.equal(kpiRowOf(assertCapsIgnored(renderDetail, claimedTask())), kpiRow(kpi('Wall-clock', '10m')));
});

test('task detail renders no Metrics section when the only metric data is a legacy cap', () => {
    assert.equal(metricsSectionOf(assertCapsIgnored(renderDetail, makeTask())), '');
});

test('task detail wall-clock KPI keeps its duration rules under every legacy cap shape', () => {
    for (const [name, metrics, , wallClock] of DURATION_CASES) {
        const html = assertCapsIgnored(renderDetail, makeTask({ metrics: { ...metrics, rejectCount: 0 } }), name);
        const kpis = wallClock == null ? [] : [kpi('Wall-clock', wallClock)];
        assert.equal(kpiRowOf(html), kpiRow(...kpis, kpi('Rejects', '0')), name);
    }
});

test('task detail keeps every live metric, critique, failed DoD item and handoff', () => {
    const section = (label, body) => '<div class="handoff-section">'
        + `<div class="handoff-section-label">${label}</div><div class="handoff-section-body">${body}</div></div>`;
    assert.equal(metricsSectionOf(assertCapsIgnored(renderDetail, richTask())), SECTION_METRICS
        + kpiRow(kpi('Steps', '2 / 3'), kpi('Wall-clock', '1h 30m'), kpi('Reopens', '2'), kpi('Rejects', '1'))
        + '<div class="critique-panel critique-block"><div class="critique-header">Plan critique: BLOCK</div>'
        + `<ul class="critique-concerns"><li>Scope &lt;too&gt; wide</li></ul><div class="muted-text">governor-1 ${at('07:00')}</div></div>`
        + '<div class="field-label" style="margin-top:8px;">Failed DoD items</div>'
        + '<ul class="failed-dod-list"><li>Tests pass (2 failures)</li><li>Docs &amp; notes</li></ul>'
        + '<div class="field-label" style="margin-top:8px;">Prior hand-offs (1)</div><div class="handoff-card">'
        + `<div class="handoff-card-title">#1 from worker-&lt;a&gt; → worker-b  (${at('08:30')})</div>`
        + section('What is done', 'Steps 1-2') + section('What remains', 'Step 3')
        + section('Pitfalls', '—') + section('Open questions', 'None') + '</div>');
});

test('task title stays escaped next to the elapsed badge and in the detail', () => {
    const task = { ...claimedTask(), title: `Cap <b>"quoted"</b> & 'single'`, budget: POPULATED_CAPS['a zero cap'] };
    const escaped = 'Cap &lt;b&gt;&quot;quoted&quot;&lt;/b&gt; &amp; &#039;single&#039;';
    assert.equal(titleOf(renderCard(task)), `<div class="task-title">${escaped}${elapsedBadge('10m')}</div>`);
    assert.equal(firstMatch(/<input type="text" id="titleInput" [^>]*>/, renderDetail(task)),
        `<input type="text" id="titleInput" value="${escaped}" />`);
});
