const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { test } = require('node:test');
const ts = require('typescript');

// Why a BLOCKED task is parked, and whether it wants a human, must be visible
// on the board card and in the task detail. The rule is the one the JetBrains
// parent (task-aec72949166b42a99b4279ba4615ac4b, TaskBlockerPresentation.kt)
// confirmed; this file pins the VS Code copies against it.
//
// Every surface here runs from its production source - media/board.js for the
// card, the webview HTML generated by TaskDetailPanel for the initial detail,
// and media/taskDetail.js for the live update - so nothing is re-implemented.
const boardScriptPath = path.join(__dirname, '../media/board.js');
const detailScriptPath = path.join(__dirname, '../media/taskDetail.js');
const panelPath = path.join(__dirname, '../src/panels/TaskDetailPanel.ts');

function transpile(sourcePath) {
    return ts.transpileModule(fs.readFileSync(sourcePath, 'utf8'), {
        compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2020, esModuleInterop: true }
    }).outputText;
}

const boardScript = fs.readFileSync(boardScriptPath, 'utf8');
const detailScript = fs.readFileSync(detailScriptPath, 'utf8');
const panelSource = transpile(panelPath);

// A stub that throws on any member it does not define, so a new IDE, DOM or
// transport dependency fails loudly instead of rendering against undefined.
function strict(name, members) {
    return new Proxy(members, {
        get(target, key) {
            if (typeof key === 'symbol' || key in target) { return Reflect.get(target, key); }
            throw new Error(`unexpected access to ${name}.${key}`);
        }
    });
}

const subscription = () => strict('Disposable', { dispose() {} });
const fakeUri = (base, ...segments) => ({ path: [base.path, ...segments].join('/') });
const fakeWebview = members => ({
    cspSource: 'vscode-webview://moe-test', asWebviewUri: uri => `vscode-webview://moe-test${uri.path}`, ...members
});

// Runs a transpiled extension module that may require only the given
// dependencies; any other require() throws.
function loadModule(source, filename, dependencies) {
    const module = { exports: {} };
    const context = vm.createContext({
        exports: module.exports, module, console,
        require: name => {
            if (Object.prototype.hasOwnProperty.call(dependencies, name)) { return dependencies[name]; }
            throw new Error(`unexpected require from ${path.basename(filename)}: ${name}`);
        }
    });
    vm.runInContext(source, context, { filename });
    return module.exports;
}

const fakeVscode = panel => ({
    ViewColumn: strict('vscode.ViewColumn', { One: 1 }), Uri: strict('vscode.Uri', { joinPath: fakeUri }),
    window: strict('vscode.window', { createWebviewPanel: () => panel })
});

// The panel module also exports the canonical TypeScript copy of the rule; the
// drift guard below asks it directly.
const panelModule = loadModule(panelSource, panelPath, { vscode: fakeVscode(null) });

// Renders one card with the real renderTaskCard of a freshly loaded board.js.
// The script's load-time retry timers are real and always cleared.
function renderCard(task, columnStatus) {
    const clears = [];
    const ignore = () => {};
    const byId = strict('document.getElementById', Object.fromEntries(['epicFilter', 'addEpicBtn', 'searchInput', 'searchClear']
        .map(id => [id, strict(`#${id}`, { addEventListener: ignore })])));
    const context = vm.createContext({
        acquireVsCodeApi: () => strict('vscodeApi', { getState: () => undefined, setState: ignore, postMessage: ignore }),
        document: strict('document', {
            addEventListener: ignore, body: strict('document.body', { addEventListener: ignore }), getElementById: id => byId[id]
        }),
        window: strict('window', { addEventListener: ignore }),
        setInterval: (fn, ms) => { const h = setInterval(fn, ms); clears.push(() => clearInterval(h)); return h; },
        setTimeout: (fn, ms) => { const h = setTimeout(fn, ms); clears.push(() => clearTimeout(h)); return h; },
        clearInterval, clearTimeout, console
    });
    try {
        vm.runInContext(boardScript, context, { filename: boardScriptPath });
        const column = columnStatus || (task.status === 'BLOCKED' ? 'WORKING' : task.status);
        return context.renderTaskCard(task, [], column);
    } finally {
        clears.forEach(clear => clear());
    }
}

// Opens the real TaskDetailPanel through createOrShow and returns the webview
// HTML it generated; the panel is disposed even when rendering throws.
function renderDetail(task) {
    const webview = fakeWebview({ html: '', onDidReceiveMessage: subscription });
    const panel = strict('WebviewPanel', { webview: strict('Webview', webview), onDidDispose: subscription, dispose() {} });
    const { TaskDetailPanel } = loadModule(panelSource, panelPath, { vscode: fakeVscode(panel) });
    const state = { tasks: [task], epics: [] };
    const client = strict('MoeDaemonClient', { currentState: state, onStateChanged: subscription });
    let opened;
    try {
        opened = TaskDetailPanel.createOrShow({ path: '/extension' }, client, task.id, state);
        return webview.html;
    } finally {
        if (opened) { opened.dispose(); }
    }
}

// ---------------------------------------------------------------------------
// A DOM small enough to read and strict enough to catch a markup assignment
// ---------------------------------------------------------------------------

// One element. `innerHTML` deliberately throws on both read and write: live
// updates must put daemon-supplied text in through a DOM text node, never by
// assembling markup, because a blockedReason is arbitrary agent output.
function makeNode(tagName, id, touched) {
    const node = {
        tagName, id, className: '', value: '', scrollTop: 0, scrollHeight: 0, dataset: {},
        children: [], text: '',
        appendChild(child) { if (id) { touched.add(id); } node.children.push(child); return child; },
        addEventListener() {}
    };
    Object.defineProperty(node, 'textContent', {
        get: () => (node.children.length > 0 ? node.children.map(child => child.textContent).join('') : node.text),
        set: value => { if (id) { touched.add(id); } node.children = []; node.text = String(value); }
    });
    const refuse = () => {
        throw new Error(`${tagName}#${id} innerHTML is not available: write daemon text with a DOM text node`);
    };
    Object.defineProperty(node, 'innerHTML', { get: refuse, set: refuse });
    return node;
}

// Loads the real media/taskDetail.js against that DOM, then delivers one
// updateTask message. Returns the nodes and the set of element ids the handler
// actually wrote to.
function runLiveUpdate(initialTask, updatedTask, editable = {}) {
    const touched = new Set();
    const nodes = {};
    const element = id => {
        if (!nodes[id]) { nodes[id] = makeNode('div', id, touched); }
        return nodes[id];
    };
    element('initial-data').dataset = { taskId: initialTask.id, taskStatus: initialTask.status };
    let onMessage;
    const context = vm.createContext({
        acquireVsCodeApi: () => strict('vscodeApi', { postMessage() {} }),
        document: strict('document', {
            getElementById: element,
            createElement: tag => makeNode(tag, null, touched),
            createTextNode: value => {
                const node = makeNode('#text', null, touched);
                node.textContent = value;
                return node;
            }
        }),
        window: strict('window', {
            addEventListener: (type, handler) => { if (type === 'message') { onMessage = handler; } }
        }),
        console
    });
    vm.runInContext(detailScript, context, { filename: detailScriptPath });
    if (typeof onMessage !== 'function') {
        throw new Error('taskDetail.js registered no message handler');
    }
    for (const [id, value] of Object.entries(editable)) { element(id).value = value; }
    touched.clear();
    onMessage({ data: { type: 'updateTask', task: updatedTask } });
    return { element, touched };
}

// ---------------------------------------------------------------------------
// Reading the two detail surfaces as the same shape: [{ cls, text }]
// ---------------------------------------------------------------------------

const unescapeHtml = text => text
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&#039;/g, "'")
    .replace(/&amp;/g, '&');

// The blocker section of the initial markup, as rendered lines.
function detailLines(html) {
    const open = '<div id="blockerSection">';
    const start = html.indexOf(open);
    assert.notEqual(start, -1, 'the detail markup has no #blockerSection wrapper');
    const inner = html.slice(start + open.length, html.indexOf('</div>\n', start));
    const lines = [];
    const pattern = /<div class="([^"]*)">([\s\S]*?)<\/div>/g;
    let match;
    while ((match = pattern.exec(inner)) !== null) {
        lines.push({ cls: match[1], text: unescapeHtml(match[2]) });
    }
    return lines;
}

// The same section after a live update, read off the DOM nodes.
const liveLines = element => element('blockerSection').children.map(child => ({ cls: child.className, text: child.textContent }));

const textOf = (lines, cls) => lines.filter(line => line.cls === cls).map(line => line.text);

// Every chip the card rendered, as { cls, title, label }.
function chipsOf(card) {
    const chips = [];
    const pattern = /<span class="chip ([^"]*)"(?: title="([^"]*)")?>([\s\S]*?)<\/span>/g;
    let match;
    while ((match = pattern.exec(card)) !== null) {
        chips.push({ cls: match[1], title: match[2] === undefined ? null : unescapeHtml(match[2]), label: match[3] });
    }
    return chips;
}

const blockerChips = card => chipsOf(card).filter(chip => chip.cls === 'chip-blocked' || chip.cls === 'chip-question');
const chipLabels = card => blockerChips(card).map(chip => chip.label);

// ---------------------------------------------------------------------------
// Fixtures
// ---------------------------------------------------------------------------

const TITLE = 'Show task blocker causes in VS Code';
const AT = '2026-09-11T10:00:00.000Z';

const DEPENDENCY_WAIT = 'Dependency wait';
const RESOURCE_WAIT = 'Resource wait';
const EXTERNAL_BLOCK = 'External block';
const ATTENTION = 'Awaiting human review';
const CLEARS = {
    [RESOURCE_WAIT]: 'Clears automatically when the shared resource lease is granted.',
    [DEPENDENCY_WAIT]: 'Clears automatically when every recorded prerequisite reaches a finished state (DONE or ARCHIVED).',
    [EXTERNAL_BLOCK]: 'Needs a person: a human or governor has to clear this block.',
    [ATTENTION]: 'Needs a person: a human or QA has to review this task.'
};
const REASON_MISSING = 'No reason was recorded.';
const PREREQUISITES_LABEL = 'Prerequisites recorded as waited on';

// A blockedReason is arbitrary agent output: multiline, and shaped like markup.
const HOSTILE_REASON = '<img src=x onerror="alert(\'moe\')"> & <script>\nsecond line \'quoted\'';

function makeTask(overrides = {}) {
    return {
        id: 'task-blocker-fixture', epicId: 'epic-blocker-fixture', title: TITLE, status: 'WORKING', priority: 'MEDIUM',
        description: 'Name the cause of a block.', definitionOfDone: ['Causes are named'], implementationPlan: [],
        assignedWorkerId: null, prLink: null, reopenCount: 0, reopenReason: null, order: 1, comments: [], ...overrides
    };
}

const dependencyTask = (extra = {}) => makeTask({
    status: 'BLOCKED', blockedFromStatus: 'WORKING', blockedAt: AT,
    blockedOnTaskIds: ['task-prereq-one', 'task-prereq-two'],
    blockedReason: 'Waiting on the parent slice.', ...extra
});
const resourceTask = (extra = {}) => makeTask({
    status: 'BLOCKED', blockedFromStatus: 'WORKING', blockedAt: AT,
    blockedResourceId: 'bench-box-1', blockedReason: 'Waiting on the benchmark box.', ...extra
});
const externalTask = (extra = {}) => makeTask({
    status: 'BLOCKED', blockedFromStatus: 'REVIEW', blockedAt: AT,
    blockedReason: 'A human has to decide.', ...extra
});

// Metadata shapes that must never produce a cause and must never throw. Each is
// spread over a BLOCKED task, so anything that survives the guards would show.
const MALFORMED_METADATA = {
    'no blocker metadata at all': {},
    'explicit nulls': { blockedResourceId: null, blockedOnTaskIds: null, blockedReason: null, blockedFromStatus: null, blockedAt: null },
    'explicit undefined': { blockedResourceId: undefined, blockedOnTaskIds: undefined, blockedReason: undefined },
    'a number for every field': { blockedResourceId: 7, blockedOnTaskIds: 7, blockedReason: 7, blockedFromStatus: 7, blockedAt: 7 },
    'an object where a list belongs': { blockedOnTaskIds: { 0: 'task-a', length: 1 }, blockedResourceId: { id: 'x' } },
    'a string where a list belongs': { blockedOnTaskIds: 'task-a,task-b' },
    'a list of non-strings': { blockedOnTaskIds: [1, null, undefined, {}, []] },
    'a blank resource id': { blockedResourceId: '' },
    'a whitespace resource id': { blockedResourceId: '   ' },
    'a tab-and-newline resource id': { blockedResourceId: '\t\n' },
    'an empty id list': { blockedOnTaskIds: [] },
    'an all-blank id list': { blockedOnTaskIds: ['', '   ', '\t'] }
};

// [name, task, expected cause label or null]. One table, three copies of the
// rule: the exported TypeScript function, media/board.js and media/taskDetail.js.
const CAUSE_TABLE = [
    ['a dependency wait', dependencyTask(), DEPENDENCY_WAIT],
    ['a resource wait', resourceTask(), RESOURCE_WAIT],
    ['a plain external block', externalTask(), EXTERNAL_BLOCK],
    ['a resource id winning over prerequisites', makeTask({
        status: 'BLOCKED', blockedResourceId: 'bench-box-1', blockedOnTaskIds: ['task-prereq-one'], blockedReason: 'Both.'
    }), RESOURCE_WAIT],
    ['a blank resource id falling through to the dependency branch', makeTask({
        status: 'BLOCKED', blockedResourceId: '   ', blockedOnTaskIds: ['task-prereq-one']
    }), DEPENDENCY_WAIT],
    ['an all-blank id list falling through to an external block', makeTask({
        status: 'BLOCKED', blockedOnTaskIds: ['', '  ']
    }), EXTERNAL_BLOCK],
    ['stale blocker metadata on a WORKING task', makeTask({
        status: 'WORKING', blockedResourceId: 'bench-box-1', blockedOnTaskIds: ['task-prereq-one'], blockedReason: 'Stale.'
    }), null],
    ['stale blocker metadata on a REVIEW task', makeTask({
        status: 'REVIEW', blockedOnTaskIds: ['task-prereq-one'], blockedReason: 'Stale.'
    }), null],
    ['stale blocker metadata on a DONE task', makeTask({
        status: 'DONE', blockedResourceId: 'bench-box-1'
    }), null],
    ['a task with no blocker metadata', makeTask(), null]
];

// ---------------------------------------------------------------------------
// The board card names the cause
// ---------------------------------------------------------------------------

test('a dependency wait renders a dependency-specific card chip', () => {
    assert.deepEqual(chipLabels(renderCard(dependencyTask())), [DEPENDENCY_WAIT]);
});

test('a resource wait renders a resource-specific card chip', () => {
    assert.deepEqual(chipLabels(renderCard(resourceTask())), [RESOURCE_WAIT]);
});

test('a plain external block renders an external-block card chip', () => {
    assert.deepEqual(chipLabels(renderCard(externalTask())), [EXTERNAL_BLOCK]);
});

test('every card cause chip says what will clear it', () => {
    for (const [name, task, expected] of CAUSE_TABLE) {
        const chips = blockerChips(renderCard(task)).filter(chip => chip.cls === 'chip-blocked');
        if (expected === null) {
            assert.deepEqual(chips, [], `${name} must render no cause chip`);
        } else {
            assert.deepEqual(chips, [{ cls: 'chip-blocked', title: CLEARS[expected], label: expected }], name);
        }
    }
});

test('the attention chip is independent and shows on a REVIEW task that is not blocked', () => {
    const card = renderCard(makeTask({ status: 'REVIEW', needsHumanReview: true }), 'REVIEW');
    assert.deepEqual(blockerChips(card), [{ cls: 'chip-question', title: CLEARS[ATTENTION], label: ATTENTION }]);
});

test('a resource wait that also records prerequisites and the flag shows the resource cause plus attention', () => {
    const card = renderCard(makeTask({
        status: 'BLOCKED', blockedResourceId: 'bench-box-1', blockedOnTaskIds: ['task-prereq-one'],
        blockedReason: 'Both a lease and a prerequisite.', needsHumanReview: true
    }));
    assert.deepEqual(chipLabels(card), [RESOURCE_WAIT, ATTENTION]);
});

test('attention is read, never inferred from status or reason text', () => {
    for (const status of ['BACKLOG', 'PLANNING', 'AWAITING_APPROVAL', 'WORKING', 'BLOCKED', 'REVIEW', 'DONE']) {
        const off = renderCard(makeTask({ status, blockedReason: 'needs human review', needsHumanReview: false }), status);
        assert.equal(chipLabels(off).includes(ATTENTION), false, `${status} must not infer attention`);
        const on = renderCard(makeTask({ status, needsHumanReview: true }), status);
        assert.equal(chipLabels(on).includes(ATTENTION), true, `${status} must honour the flag`);
    }
});

test('a truthy non-boolean review flag is not treated as attention', () => {
    for (const flag of ['true', 1, {}, []]) {
        const card = renderCard(makeTask({ status: 'REVIEW', needsHumanReview: flag }), 'REVIEW');
        assert.deepEqual(blockerChips(card), [], `needsHumanReview=${JSON.stringify(flag)}`);
    }
});

test('malformed blocker metadata never throws and never invents a wait', () => {
    for (const [name, metadata] of Object.entries(MALFORMED_METADATA)) {
        // Every malformed shape must fall all the way through to the plain
        // external block: no resource wait, no dependency wait, no throw.
        const card = renderCard(makeTask({ status: 'BLOCKED', ...metadata }));
        assert.deepEqual(chipLabels(card), [EXTERNAL_BLOCK], `BLOCKED with ${name}`);
    }
});

test('a card chip never carries the daemon-supplied reason text', () => {
    const card = renderCard(dependencyTask({ blockedReason: HOSTILE_REASON }));
    assert.equal(card.includes('onerror'), false, 'the reason must not reach the card at all');
    assert.deepEqual(chipLabels(card), [DEPENDENCY_WAIT]);
});

test('BLOCKED stays display-mapped into Working with no status sub-chip of its own', () => {
    const chips = chipsOf(renderCard(dependencyTask())).map(chip => chip.cls);
    assert.equal(chips.includes('chip-status'), false, 'BLOCKED must not add a status sub-chip in the Working column');
    assert.equal(chips.includes('chip-blocked'), true);
});

// ---------------------------------------------------------------------------
// The initial task-detail markup
// ---------------------------------------------------------------------------

test('the initial detail names the cause, its clearance and the reported reason', () => {
    const lines = detailLines(renderDetail(dependencyTask()));
    assert.deepEqual(textOf(lines, 'section-title'), ['Blocker']);
    assert.deepEqual(textOf(lines, 'blocker-cause'), [DEPENDENCY_WAIT]);
    assert.deepEqual(textOf(lines, 'muted-text'), [CLEARS[DEPENDENCY_WAIT]]);
    assert.deepEqual(textOf(lines, 'field-label'), ['Reported reason', PREREQUISITES_LABEL]);
    assert.deepEqual(textOf(lines, 'blocker-text'), [
        'Waiting on the parent slice.',
        'task-prereq-one\ntask-prereq-two',
        'Blocked from: WORKING\nBlocked at: ' + AT
    ]);
});

test('the initial detail shows the resource identity for a resource wait', () => {
    const lines = detailLines(renderDetail(resourceTask()));
    assert.deepEqual(textOf(lines, 'blocker-cause'), [RESOURCE_WAIT]);
    assert.deepEqual(textOf(lines, 'muted-text'), [CLEARS[RESOURCE_WAIT]]);
    assert.deepEqual(textOf(lines, 'blocker-text'), [
        'Waiting on the benchmark box.',
        'Resource: bench-box-1\nBlocked from: WORKING\nBlocked at: ' + AT
    ]);
});

test('an external block shows no prerequisite list and no resource fact', () => {
    const lines = detailLines(renderDetail(externalTask()));
    assert.deepEqual(textOf(lines, 'blocker-cause'), [EXTERNAL_BLOCK]);
    assert.deepEqual(textOf(lines, 'field-label'), ['Reported reason']);
    assert.deepEqual(textOf(lines, 'blocker-text'), [
        'A human has to decide.',
        'Blocked from: REVIEW\nBlocked at: ' + AT
    ]);
});

test('a missing or blank reason shows the neutral fallback, never an empty element', () => {
    for (const reason of [undefined, null, '', '   ', '\n\t', 7]) {
        const lines = detailLines(renderDetail(externalTask({ blockedReason: reason })));
        assert.deepEqual(textOf(lines, 'blocker-text')[0], REASON_MISSING, `reason=${JSON.stringify(reason)}`);
    }
});

test('recorded prerequisite ids keep their order and their duplicates, with blanks dropped', () => {
    const lines = detailLines(renderDetail(makeTask({
        status: 'BLOCKED', blockedOnTaskIds: ['task-zz', '  ', 'task-aa', 'task-zz', '', 'task-mm']
    })));
    assert.deepEqual(textOf(lines, 'blocker-text')[1], 'task-zz\ntask-aa\ntask-zz\ntask-mm');
});

test('the attention section stands alone on a REVIEW task that is not blocked', () => {
    const lines = detailLines(renderDetail(makeTask({ status: 'REVIEW', needsHumanReview: true })));
    assert.deepEqual(lines, [
        { cls: 'section-title', text: ATTENTION },
        { cls: 'blocker-cause', text: ATTENTION },
        { cls: 'muted-text', text: CLEARS[ATTENTION] }
    ]);
});

test('stale blocker metadata on a task that has left BLOCKED renders no section', () => {
    for (const status of ['WORKING', 'REVIEW', 'DONE']) {
        const html = renderDetail(makeTask({
            status, blockedResourceId: 'bench-box-1', blockedOnTaskIds: ['task-prereq-one'],
            blockedReason: 'Stale.', blockedFromStatus: 'WORKING', blockedAt: AT
        }));
        assert.deepEqual(detailLines(html), [], `${status} must render an empty blocker section`);
        assert.equal(html.includes('Stale.'), false, `${status} must not leak the stale reason`);
    }
});

test('a hostile multiline reason survives as literal escaped text in the initial markup', () => {
    const html = renderDetail(externalTask({ blockedReason: HOSTILE_REASON }));
    assert.equal(html.includes('<img src=x'), false, 'the raw tag must not reach the page');
    assert.equal(html.includes('&lt;img src=x onerror=&quot;alert(&#039;moe&#039;)&quot;&gt; &amp; &lt;script&gt;'), true);
    assert.deepEqual(textOf(detailLines(html), 'blocker-text')[0], HOSTILE_REASON);
});

test('malformed blocker metadata renders an external block without throwing', () => {
    for (const [name, metadata] of Object.entries(MALFORMED_METADATA)) {
        const lines = detailLines(renderDetail(makeTask({ status: 'BLOCKED', blockedReason: 'x', ...metadata })));
        assert.deepEqual(textOf(lines, 'blocker-cause'), [EXTERNAL_BLOCK], `BLOCKED with ${name}`);
        assert.deepEqual(textOf(lines, 'field-label'), ['Reported reason'], `BLOCKED with ${name}`);
    }
});

// ---------------------------------------------------------------------------
// The live update
// ---------------------------------------------------------------------------

test('a live update renders exactly what the initial markup renders', () => {
    const cases = [
        dependencyTask(), resourceTask(), externalTask(),
        dependencyTask({ blockedReason: HOSTILE_REASON }),
        externalTask({ blockedReason: null }),
        makeTask({ status: 'REVIEW', needsHumanReview: true }),
        makeTask({ status: 'BLOCKED', blockedResourceId: 'bench-box-1', blockedOnTaskIds: ['task-a'], needsHumanReview: true }),
        makeTask({ status: 'WORKING', blockedReason: 'Stale.', blockedOnTaskIds: ['task-a'] })
    ];
    for (const task of cases) {
        const { element } = runLiveUpdate(makeTask({ status: 'WORKING' }), task);
        assert.deepEqual(liveLines(element), detailLines(renderDetail(task)), `${task.status} live update`);
    }
});

test('a live reason arrives as a DOM text node, not as markup', () => {
    const { element } = runLiveUpdate(externalTask(), externalTask({ blockedReason: HOSTILE_REASON }));
    const reason = element('blockerSection').children.find(child => child.className === 'blocker-text');
    assert.equal(reason.text, HOSTILE_REASON);
    assert.deepEqual(reason.children, [], 'the reason must be one text value, never parsed markup');
});

test('a BLOCKED to WORKING update clears the section', () => {
    const { element } = runLiveUpdate(dependencyTask(), makeTask({
        status: 'WORKING', blockedReason: 'Waiting on the parent slice.', blockedOnTaskIds: ['task-prereq-one'],
        blockedFromStatus: 'WORKING', blockedAt: AT
    }));
    assert.deepEqual(liveLines(element), []);
});

test('attention survives the unblock and only clears when its own flag clears', () => {
    const blocked = dependencyTask({ needsHumanReview: true });
    const unblocked = runLiveUpdate(blocked, makeTask({
        status: 'WORKING', needsHumanReview: true, blockedOnTaskIds: ['task-prereq-one'], blockedReason: 'Stale.'
    }));
    assert.deepEqual(liveLines(unblocked.element), [
        { cls: 'section-title', text: ATTENTION },
        { cls: 'blocker-cause', text: ATTENTION },
        { cls: 'muted-text', text: CLEARS[ATTENTION] }
    ]);
    const cleared = runLiveUpdate(blocked, makeTask({ status: 'WORKING', needsHumanReview: false }));
    assert.deepEqual(liveLines(cleared.element), []);
});

test('a live update carrying malformed metadata clears to an external block without throwing', () => {
    for (const [name, metadata] of Object.entries(MALFORMED_METADATA)) {
        const { element } = runLiveUpdate(dependencyTask(), makeTask({ status: 'BLOCKED', ...metadata }));
        assert.deepEqual(textOf(liveLines(element), 'blocker-cause'), [EXTERNAL_BLOCK], `update with ${name}`);
    }
    const { element } = runLiveUpdate(dependencyTask(), makeTask({ status: 'PLANNING' }));
    assert.deepEqual(liveLines(element), []);
});

test('a live update never touches the title, description or Definition of Done inputs', () => {
    const typed = {
        titleInput: 'a title the human is still typ',
        descriptionInput: 'a description mid-edit',
        dodInput: 'first item\nsecond item half-writ',
        reopenReasonInput: 'half a reopen reason'
    };
    const { element, touched } = runLiveUpdate(dependencyTask(), resourceTask({ needsHumanReview: true }), typed);
    for (const [id, value] of Object.entries(typed)) {
        assert.equal(element(id).value, value, `${id} must keep its unsaved value`);
        assert.equal(element(id).textContent, '', `${id} must not be rewritten`);
    }
    assert.deepEqual([...touched].sort(), ['blockerSection', 'commentsList', 'planContent', 'statusBadge']);
});

// ---------------------------------------------------------------------------
// Drift guard: three copies of one rule, one fixture table
// ---------------------------------------------------------------------------

const CAUSE_OF_LABEL = {
    [RESOURCE_WAIT]: 'RESOURCE_WAIT', [DEPENDENCY_WAIT]: 'DEPENDENCY_WAIT', [EXTERNAL_BLOCK]: 'EXTERNAL_BLOCK'
};

test('the TypeScript rule and both webview copies agree on every fixture', () => {
    for (const [name, task, expectedLabel] of CAUSE_TABLE) {
        const expected = expectedLabel === null ? null : CAUSE_OF_LABEL[expectedLabel];

        assert.equal(panelModule.blockCause(task), expected, `TaskDetailPanel.blockCause disagrees on ${name}`);

        const cardLabels = blockerChips(renderCard(task)).filter(chip => chip.cls === 'chip-blocked').map(chip => chip.label);
        const cardCause = cardLabels.length === 0 ? null : CAUSE_OF_LABEL[cardLabels[0]];
        assert.equal(cardCause, expected, `media/board.js disagrees on ${name}`);

        const { element } = runLiveUpdate(makeTask({ status: 'WORKING' }), task);
        const liveCauses = textOf(liveLines(element), 'blocker-cause');
        const liveCause = liveCauses.length === 0 ? null : CAUSE_OF_LABEL[liveCauses[0]];
        assert.equal(liveCause, expected, `media/taskDetail.js disagrees on ${name}`);
    }
});

test('the TypeScript rule reads the attention flag verbatim and keeps recorded ids intact', () => {
    assert.equal(panelModule.needsHumanAttention(makeTask({ status: 'REVIEW', needsHumanReview: true })), true);
    assert.equal(panelModule.needsHumanAttention(makeTask({ status: 'BLOCKED', blockedReason: 'needs human review' })), false);
    assert.equal(panelModule.needsHumanAttention(makeTask({ status: 'REVIEW', needsHumanReview: 'true' })), false);
    assert.deepEqual(
        panelModule.blockedPrerequisiteIds(makeTask({ blockedOnTaskIds: ['task-zz', ' ', 'task-aa', 'task-zz'] })),
        ['task-zz', 'task-aa', 'task-zz']
    );
    // Array.from: an empty list built inside the vm realm is not reference-equal
    // to a host [], and deepStrictEqual compares prototypes.
    assert.deepEqual(Array.from(panelModule.blockedPrerequisiteIds(makeTask({ blockedOnTaskIds: 'task-a' }))), []);
    assert.deepEqual(Array.from(panelModule.blockedPrerequisiteIds(makeTask())), []);
    assert.deepEqual(Array.from(panelModule.blockedPrerequisiteIds(makeTask({ blockedOnTaskIds: ['', '  '] }))), []);
});
